name: language_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.2
  external_app_launcher: ^3.1.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2
  get: 4.6.5
  google_fonts: ^4.0.3
  grouped_list: ^5.1.2
  image_picker: ^0.8.6+3
  intl: ^0.17.0
  language_picker: ^0.4.3
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/icons/
    - assets/svg/pictures/
    - assets/png/
